"""Producer: extract a native-kernel ``SpatialKernelSpec`` from a discopt model.

The Rust spatial B&B kernel (``discopt-core::bnb::spatial_*``, issue #764) runs a
node entirely in Rust — patch box-dependent McCormick envelopes, assemble the node
LP, warm-solve, OBBT-sweep — given the *box-independent* relaxation structure once.
This module produces that structure from the uniform factorable relaxation
(``uniform_relax.build_uniform_relaxation``), which registers every lifted term with
its operand/output columns and emits the McCormick / secant-tangent envelope rows.

Classification (validated on tanksize, #764): a row is a term's **envelope** (box
dependent, regenerated by the Rust kernel per node) iff its support is contained in
that term's ``{operands, aux}`` columns; every other row — the model's linear
constraints and the linear-definitional rows of factorable intermediate aux columns
— is **box-independent** and passed through as a fixed row. Auxiliary-column bounds
come from the relaxation's own interval propagation (finite), which the safe-bound
evaluation requires.

Covered term families: bilinear products, integer-power monomials, affine squares,
and univariate ``sqrt`` — the atoms the Rust kernel implements (``EnvTerm``). A model
using any other lifted family (trilinear / multilinear / ratio / composite convex /
non-``sqrt`` univariate) returns ``None`` here, and the caller keeps the trusted
Python path. Soundness: the produced spec drives the same uniform McCormick
relaxation; the Rust patcher reproduces its envelope rows byte-for-byte (its
differential fixtures), so the native relaxation is bound-neutral with the build.
"""

from __future__ import annotations

from typing import Optional

import numpy as np
import scipy.sparse as sp

_TOL = 1e-12


def build_spatial_kernel_spec(model, bounds: Optional[tuple] = None) -> Optional[dict]:
    """Return the flat-array ``SpatialKernelSpec`` kwargs for
    ``discopt._rust.solve_spatial_tree_py``, or ``None`` if the model uses a lifted
    term family the native kernel does not implement (caller falls back to Python).

    ``bounds`` optionally overrides the original-variable box with presolved finite
    bounds ``(lb, ub)`` (each length ``n_orig``) — required for models whose raw
    ``.nl`` box is unbounded (e.g. tanksize), where the McCormick relaxation is only
    valid after the solver's FBBT/OBBT presolve.

    The returned dict also carries two ``meta_``-prefixed keys —
    ``meta_obj_sense_sign`` and ``meta_obj_offset`` — for mapping the kernel's
    internal (minimize-convention) objective/bound back to model units:
    ``model_value = sign * (internal + offset)``. Callers pass the non-``meta_`` keys
    to the kernel; :func:`solve_with_native_kernel` strips them automatically."""
    from discopt._jax.uniform_relax import build_uniform_relaxation
    from discopt.modeling.core import VarType

    # Scalar-variable models only: the relaxation's column 0..n_orig-1 maps to the n
    # variable objects one-to-one only when each has size 1. Vector variables shift
    # the layout and are a follow-up.
    if any(int(getattr(v, "size", 1)) != 1 for v in model._variables):
        return None
    n_orig = len(model._variables)

    if bounds is not None:
        lb = np.asarray(bounds[0], dtype=np.float64).copy()
        ub = np.asarray(bounds[1], dtype=np.float64).copy()
        if lb.shape != (n_orig,) or ub.shape != (n_orig,):
            return None
    else:
        lb = np.array([float(np.min(v.lb)) for v in model._variables], dtype=np.float64)
        ub = np.array([float(np.max(v.ub)) for v in model._variables], dtype=np.float64)

    def _build(box_lb, box_ub):
        # Skip the separable objective floor and convex-lift OA rows: both are
        # box-dependent rows the closed-form kernel patcher does NOT regenerate (the
        # floor is an objective row; the lift adds extra tangents beyond the
        # McCormick/secant-tangent envelope). Omitting them only loosens the
        # relaxation (a valid lower bound dropped, never invented) and makes each
        # term's envelope match the kernel's regeneration row-for-row. Mirrors the
        # incremental engine's ``_full_build``.
        return build_uniform_relaxation(
            model, box=(box_lb, box_ub), skip_separable_floor=True, skip_convex_lift=True
        )

    # STRUCTURE is identified on a PROBE box with distinct, strictly sign-matched
    # bounds so every McCormick coefficient is nonzero and each term's envelope rows
    # are cleanly separable (exactly 4 per product/square, support = {factors, aux}).
    # At the real box a factor bound of 0 would collapse rows and hide the clean
    # support. The lifted column layout and the box-INDEPENDENT rows (model
    # constraints + linear-definitional aux rows) are identical across boxes, so
    # structure + fixed rows read off the probe build are valid; only the finite
    # column bounds are taken from the real-box build. Mirrors ``_build_structure``.
    root_sign = np.where(lb >= 0.0, 1, np.where(ub <= 0.0, -1, 0))
    lb_p = np.empty(n_orig)
    ub_p = np.empty(n_orig)
    for k in range(n_orig):
        if root_sign[k] < 0:
            lb_p[k], ub_p[k] = -(7.0 + k), -1.0
        else:
            lb_p[k], ub_p[k] = 1.0, 7.0 + k

    rel = _build(lb_p, ub_p)
    milp = rel.model
    if milp._A_ub is None or not getattr(milp, "_objective_bound_valid", True):
        return None
    rel_real = _build(lb, ub)
    if rel_real.model._A_ub is None:
        return None
    # Soundness guard: if the relaxation has no valid objective bound at the real box
    # — e.g. an unbounded original variable makes a bilinear/monomial aux range
    # infinite, so the McCormick envelope is degenerate — decline rather than emit a
    # spec whose node LP is invalid. (tanksize hits this: its raw .nl box is
    # unbounded and the trusted solver first runs FBBT/presolve to finite bounds;
    # feeding the native kernel presolved bounds is the follow-up. #764.)
    if not getattr(rel_real.model, "_objective_bound_valid", False):
        return None
    if np.isinf(np.asarray(rel_real.model._bounds, dtype=np.float64)).any():
        return None

    # Decline lifted families the Rust kernel does not implement yet.
    if rel.trilinear_map or rel.multilinear_map or rel.ratio_map or rel.composite_multivar_specs:
        return None
    if any(fname != "sqrt" for (fname, *_rest) in rel.univariate_atom_specs):
        return None

    A = sp.csr_matrix(milp._A_ub, dtype=np.float64)
    A.sort_indices()
    b = np.asarray(milp._b_ub, dtype=np.float64).ravel()
    c = np.asarray(milp._c, dtype=np.float64).ravel()
    ncol = int(c.shape[0])
    csc = A.tocsc()
    indptr, indices, data = A.indptr, A.indices, A.data

    def support(r: int) -> set:
        return {int(indices[t]) for t in range(indptr[r], indptr[r + 1]) if abs(data[t]) > _TOL}

    def rows_with_col(cc: int):
        return csc.indices[csc.indptr[cc] : csc.indptr[cc + 1]]

    env_rows: set[int] = set()
    # term arrays
    tk: list[int] = []
    ti: list[int] = []
    tj: list[int] = []
    tout: list[int] = []
    tp: list[int] = []
    tcoeff: list[float] = []
    tcst: list[float] = []

    def _claim(aux: int, operands: tuple, want: Optional[int]) -> Optional[list[int]]:
        """Rows owned by this term = rows touching ``aux`` whose support ⊆ operands∪aux.
        Returns the row list, or None if ``want`` is set and the count differs."""
        allowed = set(operands) | {aux}
        rows = [int(r) for r in rows_with_col(aux) if support(r) <= allowed]
        if want is not None and len(rows) != want:
            return None
        return rows

    claimed_aux: set[int] = set()

    def _push(kind, i, j, out, p, coeff, cst, rows):
        tk.append(kind)
        ti.append(int(i))
        tj.append(int(j))
        tout.append(int(out))
        tp.append(int(p))
        tcoeff.append(float(coeff))
        tcst.append(float(cst))
        env_rows.update(rows)
        claimed_aux.add(int(out))

    # Affine-form products w = A*B (bilinear x_i*x_j AND variable × linear-form / form
    # × form) — every McCormick product the factorable engine emitted, from the
    # relaxer's bilinear_linform_specs. These generalize the single-column bilinear
    # path and cover the multi-column products (tanksize's `x_i·(Σ aₖxₖ)`) that the
    # bilinear_map alone misses. Each becomes a BlfTerm; the kernel regenerates the
    # 4 McCormick rows per box.
    blf_w: list[int] = []
    blf_a_ptr: list[int] = [0]
    blf_a_cols: list[int] = []
    blf_a_coeffs: list[float] = []
    blf_a_const: list[float] = []
    blf_b_ptr: list[int] = [0]
    blf_b_cols: list[int] = []
    blf_b_coeffs: list[float] = []
    blf_b_const: list[float] = []
    for w, a_dict, a_const, b_dict, b_const in rel.bilinear_linform_specs:
        if int(w) in claimed_aux:
            continue
        a_items = sorted((int(k), float(v)) for k, v in a_dict.items())
        b_items = sorted((int(k), float(v)) for k, v in b_dict.items())
        a_cols_t = [k for k, _ in a_items]
        b_cols_t = [k for k, _ in b_items]
        allowed = set(a_cols_t) | set(b_cols_t) | {int(w)}
        rows: Optional[list[int]] = [int(r) for r in rows_with_col(int(w)) if support(r) <= allowed]
        if not rows:
            return None
        env_rows.update(rows)
        claimed_aux.add(int(w))
        blf_w.append(int(w))
        blf_a_cols.extend(a_cols_t)
        blf_a_coeffs.extend(v for _, v in a_items)
        blf_a_ptr.append(len(blf_a_cols))
        blf_a_const.append(float(a_const))
        blf_b_cols.extend(b_cols_t)
        blf_b_coeffs.extend(v for _, v in b_items)
        blf_b_ptr.append(len(blf_b_cols))
        blf_b_const.append(float(b_const))
    for (i, p), w in rel.monomial_map.items():
        if int(w) in claimed_aux:
            continue
        rows = _claim(w, (i,), 4)
        if rows is None:
            return None
        _push(1, i, -1, w, p, 0.0, 0.0, rows)
    for (i, p), w in rel.univariate_square_map.items():
        # x_i**2 is often registered in BOTH monomial_map and univariate_square_map
        # for the same aux column — claim it once.
        if int(w) in claimed_aux:
            continue
        rows = _claim(w, (i,), 4)
        if rows is None:
            return None
        _push(1, i, -1, w, int(p), 0.0, 0.0, rows)
    for (j, w), (coeff, cst) in rel.affine_square_map.items():
        if int(w) in claimed_aux:
            continue
        rows = _claim(w, (j,), 4)
        if rows is None:
            return None
        _push(2, j, -1, w, 0, coeff, cst, rows)
    for fname, w, var, coeff, cst in rel.univariate_atom_specs:
        if int(w) in claimed_aux:
            continue
        # sqrt only (guarded above). Its concave envelope is up to 4 rows; accept
        # whatever the build emitted for this box (>=1), the kernel regenerates them.
        rows = _claim(w, (var,), None)
        if not rows:
            return None
        _push(3, var, -1, w, 0, coeff, cst, rows)

    # SOUNDNESS VALIDATION: every non-envelope row MUST be box-independent — that is
    # the whole premise of passing it through as a fixed row while the kernel
    # regenerates only the term envelopes per box. Verify by comparing the probe build
    # against the real-box build row-for-row: the lifted structure (and thus row
    # order) is identical across boxes, so a fixed row whose coefficients or rhs differ
    # between the two boxes is actually a box-DEPENDENT envelope the term maps did not
    # capture (e.g. a factorable-intermediate product tanksize lifts beyond its 9
    # bilinear + 3 sqrt terms). Freezing such a row would produce an unsound / infeasible
    # relaxation, so DECLINE — the caller keeps the trusted Python path.
    Ar = sp.csr_matrix(rel_real.model._A_ub, dtype=np.float64)
    Ar.sort_indices()
    br = np.asarray(rel_real.model._b_ub, dtype=np.float64).ravel()
    if Ar.shape != A.shape or br.shape[0] != b.shape[0]:
        return None
    rp_indptr, rp_indices, rp_data = Ar.indptr, Ar.indices, Ar.data
    for r in range(A.shape[0]):
        if r in env_rows:
            continue
        # Same nonzero pattern + values + rhs at both boxes?
        p0, p1 = indptr[r], indptr[r + 1]
        q0, q1 = rp_indptr[r], rp_indptr[r + 1]
        if (p1 - p0) != (q1 - q0):
            return None
        if not np.array_equal(indices[p0:p1], rp_indices[q0:q1]):
            return None
        if not np.allclose(data[p0:p1], rp_data[q0:q1], rtol=1e-9, atol=1e-9):
            return None
        if abs(float(b[r]) - float(br[r])) > 1e-6 * (1.0 + abs(float(br[r]))):
            return None

    # Fixed (box-independent) rows: everything not owned by a term envelope.
    fixed_row_ptr = [0]
    fixed_cols: list[int] = []
    fixed_coeffs: list[float] = []
    fixed_rhs: list[float] = []
    for r in range(A.shape[0]):
        if r in env_rows:
            continue
        row = A.getrow(r)
        fixed_cols.extend(int(cc) for cc in row.indices)
        fixed_coeffs.extend(float(v) for v in row.data)
        fixed_row_ptr.append(len(fixed_cols))
        fixed_rhs.append(float(b[r]))

    # Bounds come from the REAL-box build's interval propagation (finite) — the
    # safe-bound evaluation needs finite bounds on any column with a nonzero reduced
    # cost, and the factorable intermediate aux are only bounded by these. The column
    # layout is identical to the probe build (structure is box-independent).
    if int(np.size(rel_real.model._c)) != ncol:
        return None
    bnds = np.asarray(rel_real.model._bounds, dtype=np.float64)
    if bnds.shape != (ncol, 2):
        return None
    global_lo = bnds[:, 0].copy()
    global_hi = bnds[:, 1].copy()
    # Original columns take the (possibly presolved) branchable box.
    global_lo[:n_orig] = lb
    global_hi[:n_orig] = ub

    integrality = np.zeros(ncol, dtype=np.int64)
    for k, v in enumerate(model._variables):
        if v.var_type in (VarType.INTEGER, VarType.BINARY):
            integrality[k] = 1
    milp_int = getattr(milp, "_integrality", None)
    if milp_int is not None:
        mi = np.asarray(milp_int).ravel()
        if mi.shape[0] == ncol:
            integrality = np.maximum(integrality, (mi != 0).astype(np.int64))

    obbt_candidates = [
        k for k in range(n_orig) if np.isfinite(global_lo[k]) and np.isfinite(global_hi[k])
    ]

    if c.shape[0] != ncol:
        return None

    return dict(
        n_cols=ncol,
        n_orig=n_orig,
        c=c,
        integrality=integrality,
        global_lo=global_lo,
        global_hi=global_hi,
        fixed_row_ptr=np.asarray(fixed_row_ptr, dtype=np.int64),
        fixed_cols=np.asarray(fixed_cols, dtype=np.int64),
        fixed_coeffs=np.asarray(fixed_coeffs, dtype=np.float64),
        fixed_rhs=np.asarray(fixed_rhs, dtype=np.float64),
        term_kind=np.asarray(tk, dtype=np.int64),
        term_i=np.asarray(ti, dtype=np.int64),
        term_j=np.asarray(tj, dtype=np.int64),
        term_out=np.asarray(tout, dtype=np.int64),
        term_p=np.asarray(tp, dtype=np.int64),
        term_coeff=np.asarray(tcoeff, dtype=np.float64),
        term_cst=np.asarray(tcst, dtype=np.float64),
        blf_w=np.asarray(blf_w, dtype=np.int64),
        blf_a_ptr=np.asarray(blf_a_ptr, dtype=np.int64),
        blf_a_cols=np.asarray(blf_a_cols, dtype=np.int64),
        blf_a_coeffs=np.asarray(blf_a_coeffs, dtype=np.float64),
        blf_a_const=np.asarray(blf_a_const, dtype=np.float64),
        blf_b_ptr=np.asarray(blf_b_ptr, dtype=np.int64),
        blf_b_cols=np.asarray(blf_b_cols, dtype=np.int64),
        blf_b_coeffs=np.asarray(blf_b_coeffs, dtype=np.float64),
        blf_b_const=np.asarray(blf_b_const, dtype=np.float64),
        obbt_candidates=np.asarray(obbt_candidates, dtype=np.int64),
        # Metadata (stripped before the kernel call): map the kernel's internal
        # minimize-convention value back to model units — model = sign*(internal+off).
        meta_obj_sense_sign=float(getattr(rel, "obj_sense_sign", 1.0)),
        meta_obj_offset=float(getattr(rel, "obj_offset", 0.0)),
    )


def solve_with_native_kernel(model, bounds: Optional[tuple] = None, **config):
    """Convenience: produce the spec and run the native kernel. Returns the result
    dict from ``solve_spatial_tree_py`` (with ``meta_*`` echoed back), or ``None`` if
    the model is unsupported."""
    spec = build_spatial_kernel_spec(model, bounds=bounds)
    if spec is None:
        return None
    from discopt import _rust

    meta = {k: spec.pop(k) for k in list(spec) if k.startswith("meta_")}
    res = _rust.solve_spatial_tree_py(**spec, **config)
    res.update(meta)
    return res
