"""Complementarity / MPEC handler.

Mathematical Programs with Equilibrium Constraints (MPECs) carry complementarity
conditions of the form

    0 <= f(x)  ⊥  g(x) >= 0          (i.e. f >= 0, g >= 0, f·g = 0)

which are nonconvex and violate standard constraint qualifications, so a naive
NLP solve stalls. This module provides the two standard reformulations from the
SOTA rule inventory:

* **Scholtes regularization** — replace ``f·g = 0`` with ``f·g <= t`` and drive
  ``t -> 0`` through a homotopy of *local* NLP solves. Smooth, fast, and the
  workhorse for continuous MPECs.
* **SOS1 / disjunctive** — encode "at most one of ``f``, ``g`` is nonzero"
  exactly with a Special Ordered Set of type 1, solved by the global MINLP
  branch-and-bound. Exact, at the cost of discrete search.

Both build a standard discopt model, so no solver-core changes are required and
the global optimality machinery is reused unchanged.

Example
-------
>>> import discopt.modeling.core as dm
>>> from discopt.mpec import complementarity, solve_mpec
>>> m = dm.Model("toy")
>>> x = m.continuous("x", lb=0, ub=10)
>>> y = m.continuous("y", lb=0, ub=10)
>>> m.minimize((x - 1) ** 2 + (y - 1) ** 2)
>>> pairs = [complementarity(x, y)]          # 0 <= x ⊥ y >= 0
>>> res = solve_mpec(m, pairs, method="scholtes")
>>> round(res.objective, 3)
1.0
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional, cast

import numpy as np

from discopt.constants import CONSTRAINT_INF
from discopt.modeling.core import Expression, Model, Variable

__all__ = [
    "Complementarity",
    "ComplementarityProvenanceError",
    "ComplementarityRole",
    "box_mcp",
    "carry_complementarities",
    "complementarity",
    "flat_source_indices",
    "reformulate_gdp",
    "reformulate_scholtes",
    "reformulate_sos1",
    "require_all_relations_lowered",
    "resolve_source_variables",
    "source_variables",
    "tighten_complementarity_bounds",
    "unlowered_relations",
    "solve_mpec",
]

_INF = float("inf")

# A declared bound at or beyond this magnitude is discopt's "unbounded"
# sentinel, not a real bound: ``Model.continuous`` defaults to +/-9.999e19 and
# the LP layer's INF is ``CONSTRAINT_INF`` (1e20). A box relation whose
# complementary variable is left at that default must reduce to the NCP pair
# (l=0, u=+inf), so the sentinel is normalized to an infinity rather than
# compared literally — comparing ``ub == inf`` would classify
# ``m.continuous("a", lb=0)`` as a general box and refuse a model the symmetric
# lowering handles exactly (CLAUDE.md's "INF is the sentinel 1e20" rule).
#
# The threshold is the repo's shared ``CONSTRAINT_INF`` scaled just below the
# default bound, NOT a fourth private copy: it was 1e19, which swallowed a
# genuine finite ``ub=2e19`` and reported it as ``+inf`` (review of #1149,
# LOW 8). Anything strictly below the default sentinel magnitude is now kept as
# the finite bound the user declared.
_UNBOUNDED_SENTINEL = 0.9999 * CONSTRAINT_INF  # 9.999e19 — the declared default


def _normalize_bound(value: float) -> float:
    """Map discopt's unbounded sentinel magnitudes onto true infinities."""
    v = float(value)
    if v >= _UNBOUNDED_SENTINEL:
        return _INF
    if v <= -_UNBOUNDED_SENTINEL:
        return -_INF
    return v


class ComplementarityRole(Enum):
    """Where a complementarity relation came from, and which form it is.

    The role is *provenance*, not a lowering switch: every lowering in this
    module branches on the relation's declared operand bounds, never on the
    role. It exists so a downstream consumer (the source-residual report of
    #1148, a KKT diagnostic) can say *which* relation a residual belongs to
    after the model has been rebuilt several times.

    Attributes
    ----------
    NCP_PAIR : str
        The symmetric nonlinear-complementarity pair ``0 <= f ⊥ g >= 0``.
        Produced by :meth:`Model.complementarity` and by the ``.nl``
        type-5 importer.
    BOX_MCP : str
        The box-bounded mixed-complementarity form: a residual ``F(z)`` paired
        with a variable ``z in [l, u]``. Produced by :meth:`Model.mcp`.
        ``NCP_PAIR`` is the ``l = 0, u = +inf`` special case of it.
    FROM_KKT : str
        Generated by a KKT reformulation of an inner problem — the pairs
        :func:`discopt.bilevel.kkt.build_kkt` emits, one per lower-level
        inequality row. ``parent`` names that row.
    FROM_DISJUNCT : str
        Generated from a disjunct rather than declared by the user; ``parent``
        names the disjunction. Reserved vocabulary with no in-tree producer
        yet, exactly as ``DisjunctionSemantics.OR`` was defined by #1124
        before any lowering emitted it — a caller that generates a pair from a
        disjunct must be able to say so rather than have it read as
        user-declared.
    """

    NCP_PAIR = "ncp_pair"
    BOX_MCP = "box_mcp"
    FROM_KKT = "from_kkt"
    FROM_DISJUNCT = "from_disjunct"


class ComplementarityProvenanceError(RuntimeError):
    """A complementarity relation could not be resolved against a model.

    Raised when a rebuilding pass would carry a relation into a model that no
    longer holds one of its source operand variables — i.e. exactly when the
    relation's provenance has been broken. Never downgraded to a warning, a
    ``None`` return, or a best-effort match on generated variable *names*: the
    whole point of the relation is that a residual computed from it is a
    residual of the *source* condition, and a silently dropped or mis-resolved
    pair makes that measurement meaningless (#1147; CLAUDE.md §6–§7).
    """


@dataclass(eq=False)
class Complementarity:
    """One complementarity relation, with durable provenance to its source.

    In the symmetric NCP form this is ``0 <= f ⊥ g >= 0`` (``f, g >= 0`` and
    ``f·g = 0``). In the box-MCP form (``role`` :attr:`ComplementarityRole.BOX_MCP`)
    ``f`` is a residual ``F(z)`` and ``g`` is a variable ``z`` declared on
    ``[l, u]`` (``g_bounds``), meaning

    * ``z = l``      ⇒ ``F(z) >= 0``
    * ``l < z < u``  ⇒ ``F(z) == 0``
    * ``z = u``      ⇒ ``F(z) <= 0``

    with the NCP pair as the ``l = 0, u = +inf`` special case.

    The object is compared and hashed **by identity** (``eq=False``): a
    relation is a node in the model's IR, not a value. Two structurally
    identical pairs are two relations, and — the reason this matters — a pair
    stays usable as a dict/set key while a rebuilding pass carries it from one
    ``Model`` to the next (#1147). Value equality was never available anyway:
    ``Expression.__eq__`` builds a ``Constraint``, so a field-by-field compare
    would have returned a constraint object rather than a bool.

    Attributes
    ----------
    f, g : Expression
        The **source** operands, over the variables the user declared. They are
        never rewritten by a lowering or a rebuilding pass, so a residual
        computed from them is a residual of the source condition rather than of
        whatever relaxed row the condition was lowered into.
    name : str, optional
        The relation's name; the base name of every row generated from it.
    role : ComplementarityRole
        Where the relation came from — see :class:`ComplementarityRole`.
    f_bounds, g_bounds : tuple of float
        The bounds the *relation* declares on each operand: ``(0, +inf)`` for
        both sides of an NCP pair, ``(-inf, +inf)`` and ``(l, u)`` for a
        box-MCP. These are the relation's own semantics and are deliberately
        not the interval enclosure of the operand, which presolve moves.
    scale : float, optional
        Characteristic magnitude of the relation's residual, for a meaningful
        tolerance when the two operands carry unrelated physical magnitudes
        (a multiplier in 1e-6 against a flow in 1e3). ``None`` means "not
        declared"; :attr:`effective_scale` then derives one from the declared
        bounds.
    parent : str, optional
        Identity of the logical construct that generated the relation (the
        lower-level row for a KKT pair, the disjunction for a disjunct pair).
        ``None`` for a user-declared relation.
    f_shape, g_shape : tuple of int, optional
        Static element shapes of the operands, cached the first time the
        relation is scalarized. ``None`` means "not computed yet", which is
        distinguishable from ``()`` = "scalar".
    index : tuple of int, optional
        For an element of a vector/array relation, its multi-index into the
        parent; ``None`` for a relation that is not an element.
    source : Complementarity, optional
        For an element, the parent relation it came from — so an elementwise
        residual can be attributed back to the declared vector relation.
    lowering : str, optional
        The method (``"gdp"`` / ``"sos1"`` / ``"scholtes"``) this relation was
        lowered by, or ``None`` if it has not been lowered. See
        :meth:`mark_lowered`.
    """

    f: Expression
    g: Expression
    name: Optional[str] = None
    role: ComplementarityRole = ComplementarityRole.NCP_PAIR
    f_bounds: tuple[float, float] = (0.0, _INF)
    g_bounds: tuple[float, float] = (0.0, _INF)
    scale: Optional[float] = None
    parent: Optional[str] = None
    f_shape: Optional[tuple[int, ...]] = None
    g_shape: Optional[tuple[int, ...]] = None
    index: Optional[tuple[int, ...]] = None
    source: Optional["Complementarity"] = None
    lowering: Optional[str] = None

    # ── provenance queries ──

    @property
    def is_symmetric_nonnegative(self) -> bool:
        """True when the relation is the symmetric pair ``0 <= f ⊥ g >= 0``.

        Read off the **declared bounds**, never off :attr:`role`. Role is
        provenance — ``docs/complementarity_semantics.md`` §3 and
        :class:`ComplementarityRole` both say so — and a lowering that branched
        on it would be steered by a label. ``Complementarity`` is public and
        constructible directly, so a relation with ``g_bounds=(-1, 1)`` and the
        default ``role=NCP_PAIR`` reaches the lowerings; gating on the label let
        that through and emitted ``g >= 0`` against a declared ``lb = -1``,
        certifying a point the relation forbids (review of #1149, HIGH 2).
        """
        return self.f_bounds == (0.0, _INF) and self.g_bounds == (0.0, _INF)

    @property
    def is_box_mcp(self) -> bool:
        """True when the declared bounds are a general box, not the ``[0, inf)`` pair."""
        return not self.is_symmetric_nonnegative

    @property
    def shape(self) -> Optional[tuple[int, ...]]:
        """Element shape of the relation (the broadcast of the two operand shapes).

        ``None`` until the operand shapes have been computed (see
        :meth:`elements`); ``()`` for a scalar relation.
        """
        if self.f_shape is None or self.g_shape is None:
            return None
        if _n_elements(self.f_shape) >= _n_elements(self.g_shape):
            return self.f_shape
        return self.g_shape

    @property
    def effective_scale(self) -> float:
        """The residual scale to use: the declared one, else derived from bounds.

        The derived value is the largest finite magnitude the relation's own
        declared bounds admit (never below 1.0), so a box-MCP on ``z in [0, 1e3]``
        scales its residual tolerance by 1e3 while an unbounded relation keeps
        the absolute tolerance it has today.
        """
        if self.scale is not None:
            return float(self.scale)
        mags = [abs(b) for b in (*self.f_bounds, *self.g_bounds) if np.isfinite(b)]
        return max([1.0, *mags])

    def describe(self) -> str:
        """A short human identification of the relation, for error messages."""
        who = self.name or "<unnamed>"
        if self.index is not None:
            who = f"{who}[{', '.join(str(i) for i in self.index)}]"
        extra = f", parent={self.parent!r}" if self.parent else ""
        return f"complementarity {who!r} (role={self.role.value}{extra})"

    # ── lowering state ──

    def mark_lowered(self, model: Model, method: str) -> None:
        """Record that ``model``'s rows already encode this relation.

        Kept per-model on purpose. The same relation object may legitimately be
        lowered into two *different* models (a variant build); what is never
        legitimate is lowering it twice into the *same* model, which silently
        duplicates every generated row. The rebuilding passes propagate this
        mark when they carry a relation forward, so a lowered model's clone is
        not re-lowered either (#1147).

        The mark lives on the **model** (``Model._lowered_complementarities``,
        an identity set), not on the relation. It first lived here as a list of
        ``weakref``s, which made a ``Model`` carrying a relation unpicklable
        (``TypeError: cannot pickle 'weakref.ReferenceType'``) and made
        ``copy.deepcopy`` silently drop the mark — so the clone then refused to
        solve, a regression against a plain model copy on ``main`` (review of
        #1149, HIGH 3). Model-owned state also says the thing more directly:
        "these are the relations whose rows I already carry".
        """
        self.lowering = method
        _lowered_set(model).add(self)

    def is_lowered_into(self, model: Model) -> bool:
        """True when ``model`` already carries the rows generated from this relation."""
        return self in getattr(model, "_lowered_complementarities", ())

    # ── elementwise view ──

    def elements(self, model: Model) -> list["Complementarity"]:
        """The scalar relations this relation stands for, one per index.

        A scalar relation yields ``[self]``. A vector/array relation yields one
        child per element, each carrying its :attr:`index` and a :attr:`source`
        back-pointer, so an elementwise residual is attributable to the declared
        relation after any number of rebuilding passes.
        """
        return _scalarize_pairs(model, [self])


def _lowered_set(model: Model) -> set:
    """The model's identity set of already-lowered relations, created on demand.

    ``getattr``-with-default rather than a bare attribute read: a ``Model``
    restored from a pickle written before this attribute existed, or one built
    by a code path that bypasses ``__init__``, must not crash here.
    """
    got = getattr(model, "_lowered_complementarities", None)
    if got is None:
        got = set()
        model._lowered_complementarities = got
    return got


def complementarity(
    f: Expression,
    g: Expression,
    name: Optional[str] = None,
    *,
    role: ComplementarityRole = ComplementarityRole.NCP_PAIR,
    scale: Optional[float] = None,
    parent: Optional[str] = None,
) -> Complementarity:
    """Construct a :class:`Complementarity` condition ``0 <= f ⊥ g >= 0``.

    ``role``/``scale``/``parent`` are provenance only (#1147); they change no
    lowering. Use ``role=ComplementarityRole.FROM_KKT`` with ``parent`` naming
    the row when the pair is generated rather than user-declared.
    """
    return Complementarity(f, g, name, role=role, scale=scale, parent=parent)


def box_mcp(
    residual: Expression,
    variable: Expression,
    lb: Optional[float] = None,
    ub: Optional[float] = None,
    name: Optional[str] = None,
    *,
    scale: Optional[float] = None,
    parent: Optional[str] = None,
) -> Complementarity:
    r"""Construct the box-bounded MCP relation ``F(z) ⊥ z in [l, u]``.

    The mixed complementarity problem pairs a residual with a *bounded*
    variable rather than with a second nonnegative expression:

    * ``z = l``      ⇒ ``F(z) >= 0``
    * ``l < z < u``  ⇒ ``F(z) == 0``
    * ``z = u``      ⇒ ``F(z) <= 0``

    ``l = 0, u = +inf`` reduces exactly to the NCP pair ``0 <= F ⊥ z >= 0``,
    and is returned as a :attr:`ComplementarityRole.NCP_PAIR` relation so the
    two forms never diverge on the case they share.

    ``lb``/``ub`` default to the declared bounds of ``variable`` when it is a
    plain scalar :class:`~discopt.modeling.core.Variable`; they are required
    otherwise, since the relation's semantics *are* those bounds and guessing
    them would silently change the condition.

    This slice **represents** the relation; it does not lower it. A model
    carrying an unlowered relation is refused by :meth:`Model.solve` rather
    than solved with the condition quietly absent (#1147).
    """
    if lb is None or ub is None:
        if not (isinstance(variable, Variable) and variable.size == 1):
            raise ValueError(
                "box_mcp: lb/ub are required unless the complementary side is a plain "
                "scalar Variable whose declared bounds define the box. The relation's "
                "semantics are those bounds, so they are not guessed."
            )
        lb = float(np.min(np.asarray(variable.lb))) if lb is None else lb
        ub = float(np.max(np.asarray(variable.ub))) if ub is None else ub
    lo, hi = _normalize_bound(lb), _normalize_bound(ub)
    if not (lo <= hi):
        who = name or "<unnamed>"
        raise ValueError(f"box_mcp: empty box [{lo:g}, {hi:g}] for relation {who!r}")
    role = (
        ComplementarityRole.NCP_PAIR if (lo == 0.0 and hi == _INF) else ComplementarityRole.BOX_MCP
    )
    f_bounds = (0.0, _INF) if role is ComplementarityRole.NCP_PAIR else (-_INF, _INF)
    return Complementarity(
        residual,
        variable,
        name,
        role=role,
        f_bounds=f_bounds,
        g_bounds=(lo, hi),
        scale=scale,
        parent=parent,
    )


# ───────────────────────── provenance resolution ──────────────────────────


def _ensure_relation_name(model: Model, pair: Complementarity) -> str:
    """Give ``pair`` a name unique on ``model``, and return it.

    Every row generated from a relation is named from this, so an unnamed
    relation must not reuse a name already in play. The fallback used to be
    ``f"compl{i}"`` with ``i`` counted **within the list handed to the
    lowering** — and ``Model.complementarity`` hands over exactly one relation,
    so two unnamed declarations on the same model both became ``compl0`` and
    emitted ``compl0_f_nonneg`` twice, silently (review of #1149, MEDIUM 4).

    Fixing it here rather than at a call site fixes the class: every lowering
    entry point scalarizes through :func:`_scalarize_pairs`, so the ``.nl``
    importer, ``Model.complementarity``, and a hand-built pair handed to
    ``reformulate_*`` all get a unique name from the same rule.
    """
    if pair.name is not None:
        return pair.name
    taken = {p.name for p in model._complementarities if p.name}
    taken |= {c.name for c in model._constraints if getattr(c, "name", None)}
    k = 0
    while f"compl{k}" in taken or f"compl{k}_f_nonneg" in taken:
        k += 1
    pair.name = f"compl{k}"
    return pair.name


def _n_elements(shape: tuple[int, ...]) -> int:
    return int(np.prod(shape, dtype=np.int64)) if shape else 1


def source_variables(pair: Complementarity) -> list[Variable]:
    """Every :class:`~discopt.modeling.core.Variable` the relation's operands read.

    Traversal is iterative (a ``from_nl`` operand graph is deep enough to blow
    the recursion limit) and returns objects, in first-encounter order — never
    names or indices, which presolve renames and renumbers.

    An expression node this walker does not know how to descend into **raises**
    rather than contributing nothing. A silent miss would leave the resolution
    check below traversing less than the operand actually reads, so it would
    keep reporting "resolved" for a relation whose provenance is in fact broken
    — the probe-that-measures-nothing failure (CLAUDE.md §6).
    """
    out: list[Variable] = []
    for node in _walk_operands(pair):
        if isinstance(node, Variable):
            out.append(node)
    return out


def _walk_operands(pair: Complementarity):
    """Yield every node of the relation's two operand graphs, each exactly once.

    Iterative (a ``from_nl`` operand graph is deep enough to blow the recursion
    limit) and deterministic in first-encounter order. An
    :class:`IndexExpression` yields itself *and* its base, so a caller can see
    both "this variable is read" and "only this element of it is read".
    """
    seen: set[int] = set()
    stack: list[Expression] = [pair.g, pair.f]
    while stack:
        node = stack.pop()
        if id(node) in seen:
            continue
        seen.add(id(node))
        yield node
        stack.extend(_operand_children(pair, node))


def _operand_children(pair: Complementarity, node: Expression) -> tuple:
    """The sub-expressions of ``node``, or ``()`` for a leaf.

    A node type this dispatch does not know **raises** rather than returning
    ``()``. A silent miss would leave resolution traversing less than the
    operand actually reads, so it would keep reporting "resolved" for a relation
    whose provenance is in fact broken (CLAUDE.md §6).
    """
    from discopt.modeling.core import (
        BinaryOp,
        BooleanVar,
        Constant,
        CustomCall,
        FunctionCall,
        IndexExpression,
        MatMulExpression,
        Parameter,
        SumExpression,
        SumOverExpression,
        UnaryOp,
    )

    if isinstance(node, (Variable, Constant, Parameter, BooleanVar)):
        return ()
    if isinstance(node, IndexExpression):
        return (node.base,)
    if isinstance(node, (BinaryOp, MatMulExpression)):
        return (node.right, node.left)
    if isinstance(node, UnaryOp):
        return (node.operand,)
    if isinstance(node, SumExpression):
        return (node.operand,)
    if isinstance(node, SumOverExpression):
        return tuple(reversed(list(node.terms)))
    if isinstance(node, (FunctionCall, CustomCall)):
        return tuple(reversed(list(node.args)))
    raise ComplementarityProvenanceError(
        f"{pair.describe()}: cannot resolve provenance through expression node "
        f"{type(node).__name__!r}. Add it to the operand walker's dispatch — a "
        "node silently skipped here would make every resolution check that "
        "follows report success without having looked at the operand."
    )


def resolve_source_variables(
    model: Model, pair: Complementarity, *, context: str
) -> list[Variable]:
    """Resolve a relation's source variables against ``model``, **by identity**.

    Returns the variables in operand order. Raises
    :class:`ComplementarityProvenanceError` — naming the relation and
    ``context`` (the pass or boundary asking) — when ``model`` does not hold one
    of them. Membership is object identity, never ``name`` or ``_index``:
    presolve/FBBT eliminate and renumber variables, so an index-keyed map is
    stale exactly when it becomes useful, and a name-keyed one matches a
    generated ``_gdp_aux_disj_pair0_0_0`` that is not the source operand at all.
    """
    live = {id(v) for v in model._variables}
    resolved = source_variables(pair)
    missing = [v for v in resolved if id(v) not in live]
    if missing:
        raise ComplementarityProvenanceError(
            f"{context}: {pair.describe()} cannot be resolved against the rebuilt model — "
            f"source variable(s) {', '.join(sorted(v.name for v in missing))} are not present "
            "in it (by object identity). The relation's source operands must survive every "
            "rebuilding pass, or a residual computed from it measures the lowered rows "
            "instead of the source condition. Carry the variable objects forward, or drop "
            "the relation explicitly."
        )
    return resolved


def flat_source_indices(model: Model, pair: Complementarity) -> list[int]:
    """Flat column indices the relation's operands actually read, in ``model``.

    Derived **on demand at the solver boundary**, never persisted on the
    relation: the flat layout changes whenever a pass appends auxiliaries or
    presolve eliminates a column, so an index stored at declaration time is a
    stale answer that still looks like a valid one (#1147 scope item 4).

    Element-accurate for a statically indexed operand: ``x[2] ⊥ y`` over a
    shape-``(3,)`` ``x`` returns the two columns it reads, not all four of
    ``x`` and ``y``. Returning the whole parent variable was an
    over-report — a consumer masking a residual by these indices would touch
    columns the relation never reads (review of #1149, MEDIUM 6).

    An index that cannot be resolved statically (a slice, a computed index)
    falls back to the whole variable. That direction is deliberate: this is a
    *conservative* answer, never a narrower one than the truth, so a consumer
    can rely on the set covering everything the relation reads.
    """
    resolved = resolve_source_variables(model, pair, context="flat_source_indices")
    slots = _read_slots(pair)
    out: list[int] = []
    for v in resolved:
        off = model._flat_var_offset(v)
        elems = slots.get(id(v))
        out.extend(range(off, off + v.size) if elems is None else sorted(off + e for e in elems))
    return out


def _read_slots(pair: Complementarity) -> dict[int, Optional[set[int]]]:
    """Per-variable element slots the operands read, or ``None`` for "all of it".

    A :class:`IndexExpression` over a variable with a statically resolvable
    integer index contributes only the selected flat element; every other
    appearance of that variable — a bare reference, a slice, a computed index —
    widens it to the whole variable, which is the safe direction (see
    :func:`flat_source_indices`).
    """
    from discopt.modeling.core import IndexExpression

    slots: dict[int, Optional[set[int]]] = {}

    def note(var, elem: Optional[int]) -> None:
        if id(var) in slots and slots[id(var)] is None:
            return  # already widened to the whole variable
        if elem is None:
            slots[id(var)] = None
        else:
            slots.setdefault(id(var), set()).add(elem)  # type: ignore[union-attr]

    # Its own traversal rather than ``_walk_operands``: that walker descends
    # from an ``x[2]`` into its base ``x``, which would then be noted as a bare
    # reference and widen the slot straight back to the whole variable. Here an
    # indexed leaf is consumed WITHOUT descending, so ``x[2]`` contributes one
    # element while a bare ``x`` elsewhere in the same operand still widens it.
    seen: set[int] = set()
    stack: list[Expression] = [pair.g, pair.f]
    while stack:
        node = stack.pop()
        if id(node) in seen:
            continue
        seen.add(id(node))
        if isinstance(node, IndexExpression) and isinstance(node.base, Variable):
            note(node.base, _static_flat_element(node.base, node.index))
            continue
        if isinstance(node, Variable):
            note(node, None)
            continue
        stack.extend(_operand_children(pair, node))
    return slots


def _static_flat_element(var: Variable, index) -> Optional[int]:
    """Flat element number ``var[index]`` selects, or ``None`` when not static."""
    idx = (index,) if isinstance(index, (int, np.integer)) else index
    if not (isinstance(idx, tuple) and idx and all(isinstance(i, (int, np.integer)) for i in idx)):
        return None
    shape = var.shape or (1,)
    if len(idx) != len(shape):
        return None
    try:
        return int(np.ravel_multi_index(tuple(int(i) for i in idx), shape))
    except ValueError:
        return None  # out of range — let the model's own guard report it


def carry_complementarities(src: Model, dst: Model, *, pass_name: str) -> None:
    """Forward ``src``'s complementarity relations onto the rebuilt model ``dst``.

    Every pass that constructs a fresh :class:`~discopt.modeling.core.Model`
    from an existing one must call this. Before #1147 each of them silently
    dropped ``_complementarities``, so after any lowering the only surviving
    trace of a declared pair was its name baked into generated identifiers —
    and a residual probe written against the rebuilt model would have measured
    the relaxed row rather than the source product, printed a small number, and
    been believed.

    The **same relation objects** are forwarded (not copies), so identity-keyed
    provenance holds across any number of passes, and each is checked to resolve
    against ``dst`` first — an unresolvable one raises
    :class:`ComplementarityProvenanceError` rather than being dropped. A
    relation already lowered into ``src`` is marked lowered into ``dst`` too,
    because ``dst`` was rebuilt from ``src``'s rows and therefore already
    carries the generated ones.
    """
    relations = list(src._complementarities)
    if not relations:
        return
    for pair in relations:
        resolve_source_variables(model=dst, pair=pair, context=f"{pass_name}")
        dst._complementarities.append(pair)
        if pair.lowering is not None:
            pair.mark_lowered(dst, pair.lowering)


def unlowered_relations(model: Model) -> list[Complementarity]:
    """Relations recorded on ``model`` whose rows ``model`` does not carry.

    The solver boundary refuses these loudly: a model that *declares* a
    complementarity condition no lowering has emitted would otherwise be solved
    as if the condition were absent, and certified.
    """
    return [p for p in model._complementarities if not p.is_lowered_into(model)]


def require_all_relations_lowered(model: Model, *, context: str) -> None:
    """Refuse to solve a model that declares a relation no lowering emitted.

    Call this at **every** solver entry point, not just the convenient one. The
    guard first lived only in :meth:`Model.solve`, so the four in-tree callers of
    :func:`discopt.solver.solve_model` — the differentiable-solve paths and the
    primal heuristics — went straight past it and certified ``optimal`` on a
    point the declared relation forbids: with ``z in [-1, 1]``, ``max z`` and
    ``mcp(z + 1, z)``, ``solve_model`` returned ``z = 1`` (the MCP's ``z = u``
    branch requires ``F <= 0``; ``F = +2``). That is a CLAUDE.md §1 violation
    with no slack, so the check belongs at the boundary the solver actually
    passes through (review of #1149, HIGH 1).
    """
    if not getattr(model, "_complementarities", None):
        return
    pending = unlowered_relations(model)
    if not pending:
        return
    raise NotImplementedError(
        f"{context}: model declares complementarity relation(s) with no lowering: "
        + "; ".join(p.describe() for p in pending)
        + ". The box-bounded MCP form is represented but not lowered (#1147), so "
        "solving would silently drop the condition and certify a point it forbids. "
        "Restrict the complementary variable to [0, +inf) and use "
        "Model.complementarity, or reformulate the relation explicitly."
    )


# ─────────────────────────── scalarization ────────────────────────────


def _elem_shape(model: Model, expr: Expression) -> tuple[int, ...]:
    """Static element shape of ``expr`` (``()`` for a scalar) via interval eval."""
    from discopt._relax.convexity.interval_eval import evaluate_interval

    iv = evaluate_interval(expr, model)
    return tuple(int(d) for d in np.asarray(iv.lo).shape)


def _aux_upper_bound(model: Model, expr: Expression) -> float:
    """Finite upper bound for an SOS1 aux mirroring a nonnegative operand.

    Uses the static interval enclosure of ``expr``; returns ``+inf`` when the
    enclosure is non-finite so the SOS1→big-M lowering can raise its clear
    "add a finite upper bound" error instead of silently fabricating a huge M.
    """
    from discopt._relax.convexity.interval_eval import evaluate_interval

    try:
        hi = float(np.max(np.asarray(evaluate_interval(expr, model).hi)))
    except Exception:
        return float("inf")
    return hi if np.isfinite(hi) else float("inf")


def _index(expr: Expression, shape: tuple[int, ...], k: int) -> Expression:
    """Return element ``k`` (row-major) of a vector/array expression."""
    idx = tuple(int(v) for v in np.unravel_index(k, shape))
    elem = expr[idx[0]] if len(idx) == 1 else expr[idx]
    return cast(Expression, elem)


def _element_of(
    parent: Complementarity,
    f: Expression,
    g: Expression,
    name: str,
    index: Optional[tuple[int, ...]],
) -> Complementarity:
    """One scalar element of ``parent``, inheriting its provenance.

    Role, declared operand bounds, scale and parent identity are properties of
    the *relation*, so every element carries them; ``index`` and ``source``
    record which element of which relation this is, so an elementwise residual
    is attributable back to the declared vector relation (#1147).
    """
    return Complementarity(
        f,
        g,
        name,
        role=parent.role,
        f_bounds=parent.f_bounds,
        g_bounds=parent.g_bounds,
        scale=parent.scale,
        parent=parent.parent,
        f_shape=(),
        g_shape=(),
        index=index,
        source=parent.source if parent.source is not None else parent,
    )


def _scalarize_pairs(model: Model, pairs: list[Complementarity]) -> list[Complementarity]:
    """Expand vector/array complementarity pairs into elementwise scalar pairs.

    ``0 <= f ⊥ g >= 0`` over arrays is complementarity *elementwise*: for every
    index ``i`` independently, ``f_i·g_i = 0`` with ``f_i, g_i >= 0``. A single
    disjunction over the whole vector (``all f == 0`` ∨ ``all g == 0``) is a
    strictly stronger, wrong condition, so every reformulation scalarizes first.

    A scalar side is broadcast against a vector side (e.g. one ``f`` complementary
    to each ``g_i``). Shapes that are neither equal nor scalar-broadcastable are
    rejected loudly rather than silently mis-encoded.

    Each element inherits the parent's provenance and records its own index (see
    :func:`_element_of`), and the parent caches the operand shapes it computed
    here, so :meth:`Complementarity.elements` after a rebuilding pass returns the
    same decomposition without re-deriving it.
    """
    out: list[Complementarity] = []
    for p in pairs:
        tag = _ensure_relation_name(model, p)
        fs = p.f_shape if p.f_shape is not None else _elem_shape(model, p.f)
        gs = p.g_shape if p.g_shape is not None else _elem_shape(model, p.g)
        p.f_shape, p.g_shape = fs, gs
        nf = _n_elements(fs)
        ng = _n_elements(gs)
        n = max(nf, ng)
        if n == 1:
            # The relation IS its own single element. Returning a fresh child
            # here broke the documented contract *and* the identity-keyed
            # provenance this module advertises: ``elements(m)[0] is pair`` was
            # False, and two calls returned two different objects (review of
            # #1149, LOW 7).
            out.append(p)
            continue
        if nf not in (1, n) or ng not in (1, n):
            raise ValueError(
                f"complementarity {tag!r} has incompatible operand shapes "
                f"{fs} ⊥ {gs}: sides must have equal element counts, or one side "
                "must be scalar to broadcast."
            )
        shape = fs if nf == n else gs
        for k in range(n):
            fk = p.f if nf == 1 else _index(p.f, fs, k)
            gk = p.g if ng == 1 else _index(p.g, gs, k)
            idx = tuple(int(v) for v in np.unravel_index(k, shape))
            out.append(_element_of(p, fk, gk, f"{tag}_{k}", idx))
    return out


def _pending(model: Model, pairs: list[Complementarity]) -> list[Complementarity]:
    """The relations in ``pairs`` whose rows ``model`` does not already carry.

    Lowering a relation twice into the *same* model silently duplicates every
    row it generates — a clone of an already-lowered model, or a second
    ``solve`` over the recorded relation set, used to do exactly that. Lowering
    the same relation object into a *different* model is legitimate (a variant
    build) and is left alone, which is why the mark is keyed to the model and
    not to the relation alone (#1147).
    """
    return [p for p in pairs if not p.is_lowered_into(model)]


def _require_lowerable(pairs: list[Complementarity], method: str) -> None:
    r"""Refuse to lower a relation whose form this slice does not encode.

    Every reformulation here encodes the symmetric nonnegative pair
    :math:`0 \le f \perp g \ge 0`. A box-MCP relation on ``z in [l, u]`` is a
    three-branch condition (``z = l``, interior, ``z = u``); handing it to a
    two-branch lowering would encode a *different* feasible set and certify it.
    #1147 represents the box form and deliberately does not lower it, so the
    refusal is loud rather than an approximation (CLAUDE.md §3).

    The test is :attr:`Complementarity.is_symmetric_nonnegative` — the relation's
    **declared bounds** — never its :attr:`~Complementarity.role`. See that
    property for what gating on the label let through.
    """
    for p in pairs:
        if not p.is_symmetric_nonnegative:
            lo, hi = p.g_bounds
            raise NotImplementedError(
                f"{p.describe()} is a box-MCP relation on [{lo:g}, {hi:g}] and has no "
                f"{method!r} lowering. The symmetric pair 0 <= f _|_ g >= 0 is the "
                "l=0, u=+inf special case; the general box form is represented but not "
                "lowered in this slice (#1147). Reformulate it by hand, or restrict the "
                "complementary variable to [0, +inf)."
            )


# ─────────────────────────── reformulations ───────────────────────────


def reformulate_scholtes(model: Model, pairs: list[Complementarity], t) -> None:
    """Add Scholtes constraints ``f >= 0``, ``g >= 0``, ``f·g <= t`` for each pair.

    ``t`` may be a float or a :class:`~discopt.modeling.core.Parameter`; using a
    parameter lets :func:`solve_mpec` drive the homotopy without rebuilding the
    model. Vector/array pairs are complementarity elementwise (each ``f_i·g_i <= t``).

    Relations ``model`` already carries the rows of are skipped, not re-emitted
    (see :func:`_pending`).
    """
    todo = _pending(model, pairs)
    _require_lowerable(todo, "scholtes")
    for p in _scalarize_pairs(model, todo):
        tag = p.name
        model.subject_to(p.f >= 0, name=f"{tag}_f_nonneg")
        model.subject_to(p.g >= 0, name=f"{tag}_g_nonneg")
        model.subject_to(p.f * p.g <= t, name=f"{tag}_reg")
    for p in todo:
        p.mark_lowered(model, "scholtes")


def reformulate_sos1(model: Model, pairs: list[Complementarity]) -> None:
    """Encode each complementarity exactly with an SOS1 set.

    Requires ``f >= 0`` and ``g >= 0`` and that at most one is nonzero. When
    ``f``/``g`` are plain variables they enter the SOS1 set directly; otherwise
    nonnegative auxiliary variables ``af == f``, ``ag == g`` are introduced. Vector/
    array pairs are complementarity elementwise (one SOS1 set per index).

    Relations ``model`` already carries the rows of are skipped, not re-emitted
    (see :func:`_pending`).
    """
    todo = _pending(model, pairs)
    _require_lowerable(todo, "sos1")
    for p in _scalarize_pairs(model, todo):
        tag = p.name
        members: list[Variable] = []
        for side, expr in (("f", p.f), ("g", p.g)):
            if isinstance(expr, Variable) and expr.size == 1:
                model.subject_to(expr >= 0, name=f"{tag}_{side}_nonneg")
                members.append(expr)
            else:
                # Finite ub (from interval enclosure) keeps the SOS1→big-M
                # linking exact; left at inf only when genuinely unbounded, so
                # the downstream check surfaces a clear "add a finite ub" error.
                aux = model.continuous(
                    f"{tag}_{side}_aux", lb=0.0, ub=_aux_upper_bound(model, expr)
                )
                model.subject_to(aux == expr, name=f"{tag}_{side}_link")
                members.append(aux)
        model.sos1(members, name=f"{tag}_sos1")
    for p in todo:
        p.mark_lowered(model, "sos1")


def reformulate_gdp(model: Model, pairs: list[Complementarity]) -> None:
    """Encode each complementarity exactly as a disjunction ``(f==0) ∨ (g==0)``.

    With ``f, g >= 0`` this is equivalent to ``f·g == 0``. The disjunction is
    added via :meth:`Model.either_or` and lowered to a big-M model with a
    selector binary by the GDP pass at solve time, so branch-and-bound branches
    on the finite either/or choice and the integrality-aware FBBT can infer one
    side is zero when the other is bounded away from zero (the backward
    complementarity rule).

    Nonlinear operands are lifted into a scalar auxiliary variable
    ``u == expr`` (with finite interval bounds) so the disjunct ``u == 0`` stays
    linear and big-M is exact; plain scalar variables enter the disjunction
    directly. Lifting also keeps the nonlinear part as an ordinary smooth
    equality handled natively by the NLP relaxation — avoiding the perspective
    of a nonlinear equality, whose big-M relaxation is bounded unreliably and
    whose hull form often cannot be linearized.

    Vector/array pairs are complementarity elementwise: each index becomes its own
    ``(f_i==0) ∨ (g_i==0)`` disjunction, not a single all-zero-vector disjunction.

    Relations ``model`` already carries the rows of are skipped, not re-emitted
    (see :func:`_pending`).
    """
    todo = _pending(model, pairs)
    _require_lowerable(todo, "gdp")
    for p in _scalarize_pairs(model, todo):
        # _scalarize_pairs always assigns a name; narrow Optional[str] -> str.
        tag = p.name or "compl"
        fv = _gdp_operand(model, p.f, tag, "f")
        gv = _gdp_operand(model, p.g, tag, "g")
        model.subject_to(fv >= 0, name=f"{tag}_f_nonneg")
        model.subject_to(gv >= 0, name=f"{tag}_g_nonneg")
        model.either_or([[fv == 0], [gv == 0]], name=tag)
    for p in todo:
        p.mark_lowered(model, "gdp")


def _gdp_operand(model: Model, expr: Expression, tag: str, side: str) -> Expression:
    """Return a linear operand for a GDP complementarity disjunct.

    Linear expressions are used directly; nonlinear bodies are lifted to a
    scalar auxiliary variable with finite interval bounds.
    """
    from discopt._relax.gdp_reformulate import _is_linear

    if _is_linear(expr):
        return expr
    lo, hi = model._branch_bounds(expr, expr)
    model._aux_counter += 1
    u = model.continuous(f"_{tag}_{side}_{model._aux_counter}", lb=lo, ub=hi)
    model.subject_to(u == expr, name=f"{tag}_{side}_lift")
    return u


def tighten_complementarity_bounds(model: Model, pairs: list[Complementarity]) -> int:
    """Complementarity bound propagation for plain variable pairs.

    If one side of ``0 <= x ⊥ y >= 0`` is provably strictly positive
    (``lb > 0``), the other side must be zero. Applied only to single-variable
    sides, where the implication is sound and exact. Returns the number of
    variables fixed to zero.

    The partner is fixed by *intersecting* its upper bound with 0 — the lower
    bound is never overwritten. If the partner already carries a strictly
    positive lower bound the complementarity is genuinely infeasible (both sides
    would be > 0); that is surfaced as a ``ValueError`` rather than silently
    collapsing the box to ``[0, 0]`` and hiding the infeasibility (MP-1).

    Raises
    ------
    ValueError
        If a fixed-to-zero partner has a strictly positive declared lower bound,
        i.e. the complementarity pair is infeasible.
    """
    fixed = 0
    for p in pairs:
        if not p.is_symmetric_nonnegative:
            # The implication "one side strictly positive => partner is 0" is a
            # property of the *nonnegative* pair. On a box relation the partner is
            # pinned to a bound of [l, u], not to 0, so applying this rule would
            # fabricate a bound and could cut the solution out of the box. Keyed
            # to the declared bounds, not to ``role`` (review of #1149, HIGH 2).
            continue
        f_var = p.f if isinstance(p.f, Variable) and p.f.size == 1 else None
        g_var = p.g if isinstance(p.g, Variable) and p.g.size == 1 else None
        if f_var is not None and float(f_var.lb) > 0.0 and g_var is not None:
            _fix_partner_to_zero(g_var, driver=f_var, tag=p.name)
            fixed += 1
        elif g_var is not None and float(g_var.lb) > 0.0 and f_var is not None:
            _fix_partner_to_zero(f_var, driver=g_var, tag=p.name)
            fixed += 1
    return fixed


def _fix_partner_to_zero(partner: Variable, *, driver: Variable, tag: str | None) -> None:
    """Force a complementarity partner to 0 by intersecting its ub with 0.

    ``driver`` is strictly positive (``lb > 0``), so ``0 <= f ⊥ g >= 0`` forces
    ``partner == 0``. Intersect ``partner.ub`` with 0 without touching
    ``partner.lb``; if that lower bound is itself positive the box is empty and
    the pair is infeasible — raise rather than overwrite ``lb`` (MP-1).
    """
    if float(partner.lb) > 0.0:
        raise ValueError(
            f"Complementarity {tag or '<unnamed>'} is infeasible: one side has "
            f"lb={float(driver.lb):g} > 0, forcing the partner to 0, but the partner "
            f"has lb={float(partner.lb):g} > 0 — 0 <= f _|_ g >= 0 cannot hold."
        )
    partner.ub = np.minimum(np.array(partner.ub, dtype=np.float64), 0.0)


# ─────────────────────────────── solve ───────────────────────────────


def solve_mpec(
    model: Model,
    pairs: list[Complementarity],
    *,
    method: str = "scholtes",
    t0: float = 1.0,
    sigma: float = 0.1,
    t_min: float = 1e-8,
    max_iter: int = 16,
    x0: Optional[np.ndarray] = None,
    nlp_options: Optional[dict] = None,
    **solve_kwargs,
):
    """Solve an MPEC by reformulating its complementarity conditions.

    Parameters
    ----------
    model : Model
        Model carrying the objective and any ordinary constraints. It is
        augmented in place with the reformulation constraints.
    pairs : list[Complementarity]
        The complementarity conditions ``0 <= f ⊥ g >= 0``.
    method : {"scholtes", "sos1", "gdp"}
        ``"scholtes"`` runs a homotopy of *local* NLP solves with the
        regularization ``t`` shrinking ``t0 -> t0·sigma -> ...`` until ``t_min``.
        ``"sos1"`` encodes each pair as a Special Ordered Set of type 1 and
        ``"gdp"`` as the exact disjunction ``(f==0) ∨ (g==0)``; both build a
        standard model and call the global MINLP solver (``solve_kwargs``
        forwarded to :meth:`Model.solve`). ``"gdp"`` typically explores far
        fewer nodes than the smooth bilinear encoding.

    Returns
    -------
    The solver result. For ``"scholtes"`` this is the final NLP result
    (with ``.x`` and ``.objective``); for ``"sos1"`` / ``"gdp"`` it is the
    :meth:`Model.solve` result.
    """
    if method == "sos1":
        reformulate_sos1(model, pairs)
        return model.solve(**solve_kwargs)

    if method == "gdp":
        reformulate_gdp(model, pairs)
        return model.solve(**solve_kwargs)

    if method != "scholtes":
        raise ValueError(f"unknown MPEC method {method!r}; use 'scholtes', 'sos1', or 'gdp'")

    # Scholtes regularization homotopy via local NLP solves.
    from discopt._tape_nlp_evaluator import make_evaluator
    from discopt.solvers.nlp_backend import get_nlp_solver

    t = model.parameter("_mpec_t", value=t0)
    reformulate_scholtes(model, pairs, t)

    backend = get_nlp_solver("auto")
    opts = dict(nlp_options) if nlp_options else {}
    opts.setdefault("print_level", 0)

    lb, ub = _flat_bounds(model)
    x_cur = (
        np.clip(np.asarray(x0, dtype=np.float64), lb, ub) if x0 is not None else _midpoint(lb, ub)
    )

    result = None
    tv = t0
    for _ in range(max_iter):
        t.value = np.asarray(tv, dtype=np.float64)
        # Re-request the evaluator so the updated parameter value is compiled in.
        # #1063: the canonical funnel, not the JAX ctor. The cache fingerprint
        # excludes ``Parameter.value`` on purpose, but ``TapeNLPEvaluator``
        # snapshots values and rebuilds when they move, so the homotopy still sees
        # the current ``t``.
        evaluator = make_evaluator(model)
        try:
            result = backend(evaluator, x_cur, options=opts)
        except Exception as e:
            # MP-2: never swallow silently. A first-iteration failure has no
            # result to fall back on — surface it; a later continuation failure
            # keeps the best point found so far (valid at a larger t).
            if result is None:
                raise RuntimeError(
                    f"MPEC NLP solve failed on the first homotopy iteration (t={tv:g}): {e}"
                ) from e
            break
        if result.x is not None:
            x_cur = np.asarray(result.x, dtype=np.float64)
        if tv <= t_min:
            break
        tv = max(tv * sigma, t_min)
    return result


def _flat_bounds(model: Model) -> tuple[np.ndarray, np.ndarray]:
    lbs, ubs = [], []
    for v in model._variables:
        lbs.append(np.asarray(v.lb).flatten())
        ubs.append(np.asarray(v.ub).flatten())
    return np.concatenate(lbs), np.concatenate(ubs)


def _midpoint(lb: np.ndarray, ub: np.ndarray) -> np.ndarray:
    lo = np.clip(lb, -1e6, 1e6)
    hi = np.clip(ub, -1e6, 1e6)
    return np.asarray(0.5 * (lo + hi), dtype=np.float64)
