#!/usr/bin/env bash
# Install CUTEst, SIFDecode, and the SIF test problem collection.
#
# Usage:
#   bash scripts/setup_cutest.sh            # install to ~/.local/cutest
#   CUTEST_PREFIX=/opt/cutest bash scripts/setup_cutest.sh
#
# After running, source the generated env file:
#   source ~/.local/cutest/env.sh
#
# Prerequisites: gfortran, meson, ninja (brew install gcc meson)

set -euo pipefail

PREFIX="${CUTEST_PREFIX:-$HOME/.local/cutest}"
CACHE="${PYCUTEST_CACHE:-/tmp/pycutest_cache}"

echo "==> CUTEst setup"
echo "    Prefix:  $PREFIX"
echo "    Cache:   $CACHE"
echo ""

# ── Prerequisites ─────────────────────────────────────────────────────
check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        echo "ERROR: $1 not found.  Install with: $2"
        exit 1
    fi
}

check_cmd gfortran "brew install gcc"
check_cmd meson    "brew install meson"
check_cmd ninja    "brew install meson"   # meson installs ninja
check_cmd git      "xcode-select --install"

echo "==> Prerequisites OK (gfortran, meson, ninja, git)"

# Set deployment target to current macOS version to avoid linker warnings
export MACOSX_DEPLOYMENT_TARGET
MACOSX_DEPLOYMENT_TARGET="$(sw_vers -productVersion 2>/dev/null || echo 11.0)"

mkdir -p "$PREFIX"
cd "$PREFIX"

# ── Clone repos (skip if already present) ─────────────────────────────
clone_if_missing() {
    local dir="$1" url="$2"
    if [ -d "$dir/.git" ]; then
        echo "==> $dir already cloned, pulling latest..."
        git -C "$dir" pull --ff-only 2>/dev/null || true
    else
        echo "==> Cloning $url -> $dir"
        git clone --depth 1 "$url" "$dir"
    fi
}

clone_if_missing sifdecode https://github.com/ralna/SIFDecode.git
clone_if_missing cutest    https://github.com/ralna/CUTEst.git
clone_if_missing mastsif   https://bitbucket.org/optrove/sif.git

# ── Build SIFDecode ───────────────────────────────────────────────────
echo ""
echo "==> Building SIFDecode..."
cd "$PREFIX/sifdecode"
if [ -d builddir ]; then
    echo "    (wiping previous builddir)"
    rm -rf builddir
fi
meson setup builddir --prefix="$PREFIX/install"
meson compile -C builddir
meson install -C builddir
echo "==> SIFDecode installed"

# ── Build CUTEst ─────────────────────────────────────────────────────
echo ""
echo "==> Building CUTEst..."
cd "$PREFIX/cutest"
if [ -d builddir ]; then
    echo "    (wiping previous builddir)"
    rm -rf builddir
fi
meson setup builddir --prefix="$PREFIX/install"
meson compile -C builddir
meson install -C builddir
echo "==> CUTEst installed"

# ── pycutest cache ────────────────────────────────────────────────────
mkdir -p "$CACHE"

# ── Write env.sh ─────────────────────────────────────────────────────
ENV_FILE="$PREFIX/env.sh"
cat > "$ENV_FILE" <<ENVEOF
# CUTEst environment — source this file before using pycutest
# Generated by scripts/setup_cutest.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

export CUTEST="$PREFIX/install"
export SIFDECODE="$PREFIX/install"
export MASTSIF="$PREFIX/mastsif"
export PYCUTEST_CACHE="$CACHE"
export PATH="\$CUTEST/bin:\$SIFDECODE/bin:\$PATH"
export LD_LIBRARY_PATH="\$CUTEST/lib:\$SIFDECODE/lib:\${LD_LIBRARY_PATH:-}"
export DYLD_LIBRARY_PATH="\$CUTEST/lib:\$SIFDECODE/lib:\${DYLD_LIBRARY_PATH:-}"
ENVEOF

echo ""
echo "============================================================"
echo "  CUTEst setup complete!"
echo ""
echo "  Env file: $ENV_FILE"
echo "  SIF problems: $PREFIX/mastsif"
echo "  Cache: $CACHE"
echo ""
echo "  To activate, add to your shell profile:"
echo "    source $ENV_FILE"
echo ""
echo "  Or run benchmarks directly:"
echo "    source $ENV_FILE && make bench-cutest-smoke"
echo "============================================================"
