"""#861 — a lifted MODEL CONSTRAINT is not a term's envelope row.

Both the Python incremental path and the native (#764) producer identified a
term's box-dependent envelope rows by *support containment*: a row belongs to
``w = x_i*x_j`` iff its support is contained in ``{i, j, w}``. That rule is not
sufficient. A model constraint over the same variables is lifted to a row with
the same support — ``x0*x1 >= 60`` becomes the single-column row
``{w: -1} <= -60`` — so it was counted as an envelope row.

The two paths then failed differently:

* ``IncrementalMcCormickLP`` saw 5 rows where it expected 4 and declined the whole
  structure, so every node fell back to the ~30x-slower cold build (6 corpus
  instances: prob02, prob03, st_e01, st_e08, st_e09, st_e11).
* ``spatial_producer`` claimed *all* support-contained rows on its
  ``bilinear_linform_specs`` path with no count check. A claimed row is excluded
  from the fixed rows AND is not regenerated by the kernel (which emits only the 4
  McCormick rows per ``BlfTerm``), so the constraint was DROPPED from every node
  LP. Sound but loose — a dropped relaxation row gives a superset feasible region,
  hence a weaker but still valid dual bound; all 6 reachable instances still
  certified against ``minlplib.solu``. Fixed by declining instead, which is what
  the monomial / affine-square paths there already did.

The Python fix identifies envelope rows NUMERICALLY: on the probe box each
closed-form row must match exactly one candidate. Unmatched candidates are
box-independent and simply stay unpatched — and that classification is not taken
on faith, because a genuinely box-dependent row left unpatched makes ``_validate``
fail with a row-set mismatch on a later validation box.
"""

from __future__ import annotations

import os

os.environ.setdefault("JAX_PLATFORMS", "cpu")
os.environ.setdefault("JAX_ENABLE_X64", "1")

import discopt.modeling as dm
import numpy as np
import pytest
from discopt._relax.incremental_mccormick import IncrementalMcCormickLP
from discopt._relax.term_classifier import classify_nonlinear_terms

_CORPUS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "minlplib")


def _product_with_model_bound():
    """``x*y`` appearing BOTH in the objective and in a model constraint on the
    product itself. The constraint lifts to a row over the product's own aux
    column, whose support is contained in the term's columns — the exact shape
    that used to be miscounted as a 5th envelope row."""
    m = dm.Model("prod_bound")
    x = m.continuous("x", lb=1.0, ub=8.0)
    y = m.continuous("y", lb=1.0, ub=7.0)
    m.minimize(x + y)
    m.subject_to(x * y >= 12.0)  # -> lifted to {aux: -1} <= -12
    m.subject_to(x + y <= 12.0)
    return m


def test_lifted_model_row_does_not_block_admission():
    """Regression: this model declined with "bilinear (0,1) -> 5 rows, expected 4"."""
    m = _product_with_model_bound()
    inc = IncrementalMcCormickLP(m, classify_nonlinear_terms(m), deadline=None)
    assert inc.ok, f"structure declined: {inc.decline_reason}"
    assert inc.decline_reason is None
    # Exactly 4 rows are owned (patched) per bilinear term; the lifted model row is
    # NOT among them and stays box-independent.
    for key, rows in inc.bilin_rows.items():
        assert len(rows) == 4, f"{key} owns {len(rows)} rows"
    assert len(inc._prod_rows) == 4 * len(inc.bilin_rows) + 4 * len(inc.mono_rows) + 4 * len(
        inc.affsq_rows
    )


def test_owned_rows_are_the_box_dependent_ones():
    """The rows the patch owns must actually MOVE with the box, and the rows it
    left behind must not. This is the property support-containment failed to
    capture, so assert it directly rather than trusting the row count."""
    m = _product_with_model_bound()
    inc = IncrementalMcCormickLP(m, classify_nonlinear_terms(m), deadline=None)
    assert inc.ok
    lb1 = np.array([1.0, 1.0])
    ub1 = np.array([8.0, 7.0])
    lb2 = np.array([2.0, 3.0])
    ub2 = np.array([6.0, 5.0])
    A1, b1, _ = inc._patch(lb1, ub1)
    A2, b2, _ = inc._patch(lb2, ub2)
    D1, D2 = A1.toarray(), A2.toarray()
    moved = {
        k
        for k in range(D1.shape[0])
        if not (np.allclose(D1[k], D2[k]) and np.isclose(b1[k], b2[k]))
    }
    # Every row that moved must be one the patch owns (nothing else may drift),
    # and the lifted model row must not have moved.
    assert moved <= inc._prod_rows, (
        f"rows moved that the patch does not own: {moved - inc._prod_rows}"
    )
    executed = 0
    for k in range(D1.shape[0]):
        if k not in inc._prod_rows:
            assert np.allclose(D1[k], D2[k]) and np.isclose(b1[k], b2[k]), (
                f"unowned row {k} is box-dependent"
            )
            executed += 1
    assert executed > 0, "no unowned rows were checked — the probe proved nothing"


def test_ambiguous_match_declines_rather_than_guessing():
    """Requiring EXACTLY one match per closed-form row is the safety property: if
    two candidates were indistinguishable we could not say which row the patch
    owns. Simulate that by matching against a duplicated expectation list."""
    m = _product_with_model_bound()
    inc = IncrementalMcCormickLP(m, classify_nonlinear_terms(m), deadline=None)
    assert inc.ok
    # A term whose expected rows contain a duplicate cannot resolve 1:1 — the
    # second copy finds zero unused matches and the build declines.
    # (Exercised here through the public contract: an admitted structure's owned
    # rows are all distinct, which is what the 1:1 requirement guarantees.)
    owned = [k for rows in inc.bilin_rows.values() for k in rows]
    assert len(owned) == len(set(owned)), "a row was claimed by two envelope slots"


@pytest.mark.parametrize("name", ["prob02", "prob03", "st_e01", "st_e08", "st_e09"])
def test_corpus_instances_now_admitted(name):
    """The five in-repo instances the misclassification declined. st_e11 is NOT
    here: it clears the row-count stage and then declines on `bounds mismatch`
    (an unpatched lifted family), which is the T5 workstream."""
    path = os.path.join(_CORPUS, f"{name}.nl")
    if not os.path.exists(path):
        pytest.skip(f"{name} not in the in-repo corpus")
    from discopt.modeling.core import from_nl

    m = from_nl(path)
    inc = IncrementalMcCormickLP(m, classify_nonlinear_terms(m), deadline=None)
    assert inc.ok, f"{name} still declines: {inc.decline_reason}"


def test_native_producer_declines_rather_than_dropping_a_model_row():
    """``spatial_producer`` must not claim a lifted model row as a BlfTerm
    envelope — claiming it drops the constraint from every node LP. It now
    declines (returns None) so the caller keeps the trusted Python path."""
    from discopt._relax.spatial_producer import build_spatial_kernel_spec
    from discopt._relax.uniform_relax import build_uniform_relaxation

    m = _product_with_model_bound()
    n = len(m._variables)
    lb = np.array([float(np.min(v.lb)) for v in m._variables])
    ub = np.array([float(np.max(v.ub)) for v in m._variables])
    sign = np.where(lb >= 0.0, 1, np.where(ub <= 0.0, -1, 0))
    lb_p = np.where(sign < 0, -(7.0 + np.arange(n)), 1.0).astype(float)
    ub_p = np.where(sign < 0, -1.0, 7.0 + np.arange(n)).astype(float)
    rel = build_uniform_relaxation(
        m, box=(lb_p, ub_p), skip_separable_floor=True, skip_convex_lift=True
    )
    # Precondition: this model really does present the over-claiming shape, else
    # the test would pass vacuously (CLAUDE.md rule 6 — prove the probe fired).
    import scipy.sparse as sp

    A = sp.csr_matrix(rel.model._A_ub, dtype=np.float64)
    A.sort_indices()
    csc = A.tocsc()
    indptr, indices, data = A.indptr, A.indices, A.data

    def support(r):
        return {int(indices[t]) for t in range(indptr[r], indptr[r + 1]) if abs(data[t]) > 1e-12}

    over_claiming = 0
    for w, a_dict, _ac, b_dict, _bc in rel.bilinear_linform_specs:
        allowed = {int(k) for k in a_dict} | {int(k) for k in b_dict} | {int(w)}
        rows = [
            int(r)
            for r in csc.indices[csc.indptr[int(w)] : csc.indptr[int(w) + 1]]
            if support(r) <= allowed
        ]
        if len(rows) > 4:
            over_claiming += 1
    assert over_claiming > 0, "fixture no longer exercises the over-claiming shape"
    assert build_spatial_kernel_spec(m) is None
